### ISSUE TITLE
Trying to set in game, disconnects

### ISSUE THREAD

**Issue by MayhemBill** [captain1242/MSync#4]
I get this as an error if I click on anything in game 

Disconnect: [MSync] CSLua: Tried to force-get server settings table (A2).
 

I set the ranks for access, and the db in the lua files.

**Comment by ApertureDevelopment** [comment]
This error happens when you try to get the settings table ( via net reciver ) without the needed permission to view them. Please make sure that you have ALL permissions needed.

**Comment by ApertureDevelopment** [comment]
Btw to get faster support, please consider to sign up at Aperture Development ( https://www.Aperture-Development.de ) our ticketsystem gets checked multible times a day
